const ASSUMED_BACKGROUND_COLOR = [255, 255, 255];
const BGCOLOR = "bgColor";
const TEXTCOLOR = "textColor";
const LINKCOLOR = "linkColor";

export { ASSUMED_BACKGROUND_COLOR, BGCOLOR, TEXTCOLOR, LINKCOLOR };
